//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabxPonto_Commons.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrosMessage_Pessoa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrosMessage_Pessoa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabxPonto_Commons.Resource.ErrosMessage_Pessoa", typeof(ErrosMessage_Pessoa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF deve ter 11 caracteres..
        /// </summary>
        public static string PesCPFTamanho {
            get {
                return ResourceManager.GetString("PesCPFTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF deve ser preenchido..
        /// </summary>
        public static string PesCPFVazio {
            get {
                return ResourceManager.GetString("PesCPFVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data de Nascimento deve ser informada..
        /// </summary>
        public static string PesDataNascimentoVazio {
            get {
                return ResourceManager.GetString("PesDataNascimentoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estado Civil deve ser informado..
        /// </summary>
        public static string PesEstadoCivil {
            get {
                return ResourceManager.GetString("PesEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome da Mãe deve ter entre 5 e 50 caracteres..
        /// </summary>
        public static string PesNomeMaeTamanho {
            get {
                return ResourceManager.GetString("PesNomeMaeTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome da Mãe deve ser preenchido..
        /// </summary>
        public static string PesNomeMaeVazio {
            get {
                return ResourceManager.GetString("PesNomeMaeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Pai deve ter entre 5 e 50 caracteres..
        /// </summary>
        public static string PesNomePaiTamanho {
            get {
                return ResourceManager.GetString("PesNomePaiTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Pai deve ser preenchido..
        /// </summary>
        public static string PesNomePaiVazio {
            get {
                return ResourceManager.GetString("PesNomePaiVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome deve ter entre 5 e 50 caracteres..
        /// </summary>
        public static string PesNomeTamanho {
            get {
                return ResourceManager.GetString("PesNomeTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome deve ser preenchido..
        /// </summary>
        public static string PesNomeVazio {
            get {
                return ResourceManager.GetString("PesNomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número da Identidade deve ter entre 2 e 50 caracteres..
        /// </summary>
        public static string PesRGTamanho {
            get {
                return ResourceManager.GetString("PesRGTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número da Identidade deve ser preenchido..
        /// </summary>
        public static string PesRGVazio {
            get {
                return ResourceManager.GetString("PesRGVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Sobre Nome deve ter entre 5 e 50 caracteres..
        /// </summary>
        public static string PesSobreNomeTamanho {
            get {
                return ResourceManager.GetString("PesSobreNomeTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Sobre Nome deve ser preenchido..
        /// </summary>
        public static string PesSobreNomeVazio {
            get {
                return ResourceManager.GetString("PesSobreNomeVazio", resourceCulture);
            }
        }
    }
}
